name: Production Tag Deployment (DOC)
env:
  COOLIFY_SERVER_URL: ${{ secrets.COOLIFY_SERVER_URL }}
  COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
  COOLIFY_PROJECT_ID: ${{ secrets.COOLIFY_PROJECT_ID_DOC }}
on:
  push:
    # Pattern matched against refs/tags
    tags-ignore:
      - '*-staging*' # Exclude tags containing "staging"
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Print Tag Name
        run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      - name: cURL request
        if: ${{ env.COOLIFY_SERVER_URL && GITHUB_REF_NAME && env.COOLIFY_TOKEN && env.COOLIFY_PROJECT_ID }}
        run: |
          curl --request GET \
            --url ${{ env.COOLIFY_SERVER_URL }}/api/v1/deploy?uuid=${{ env.COOLIFY_PROJECT_ID }}&tag=${GITHUB_REF_NAME} \
            --header "Authorization: Bearer ${{ env.COOLIFY_TOKEN }}"
